services:
  - type: web
    name: five9-config-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIVE9_CLIENT_ID
        sync: false
      - key: FIVE9_CLIENT_SECRET
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://five9-config-frontend.onrender.com

  - type: static
    name: five9-config-frontend
    buildCommand: ""
    staticPublishPath: frontend
